# Generated by Django 2.2.6 on 2020-02-04 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ideas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideasmodel',
            name='date_posted',
        ),
    ]
