# Generated by Django 2.2.6 on 2020-02-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dossiers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossiersmodel',
            name='date_originally_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
